<a href="https://colab.research.google.com/github/abdel2ty/IntenseAI_Notebooks_v1/blob/main/linear_algebra_with_numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<a href="https://www.zero-grad.com/">
         <img alt="Zero Grad" src="https://i.postimg.cc/y8LZ0CM6/linear-Algebra.png" >
      </a>

In [ ]:
import numpy as np

# Indexing & Slicing

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
a[2]            # Select the element at the 2nd index

3

In [ ]:
a[0:2]          # Select items at index 0 and 1

array([1, 2])

In [ ]:
a[::-1]         # Reversed Array

array([3, 2, 1])

In [ ]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
b[1,2]          # Select the element at row 1 column 2 (equivalent to b[1][2])

6.0

In [ ]:
b[:2, 1]        # Select items at rows 0 and 1 in column 1

array([2., 5.])

In [ ]:
b[:1]           # Select all items at row 0 (equivalent to b[0:1,:])

array([[1.5, 2. , 3. ]])

In [ ]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]])
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [ ]:
c[1, ...]           # Same as [1,:,:]

array([[3., 2., 1.],
       [4., 5., 6.]])

# Boolean Indexing (with Condition)

In [ ]:
a

array([1, 2, 3])

In [ ]:
a<2

array([ True, False, False])

In [ ]:
a[a<2]

array([1])

In [ ]:
a[a%2 ==1]

array([1, 3])

In [ ]:
b = np.array([3,1,5])
b

array([3, 1, 5])

In [ ]:
np.where(a<b)

(array([0, 2]),)

In [ ]:
np.intersect1d(a,b)

array([1, 3])

In [ ]:
np.union1d(a,b)

array([1, 2, 3, 5])

# Fancy Indexing

In [ ]:
C = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [0,0,0]])

In [ ]:
C[[1,2]]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
C[[0,3]]

array([[1, 2, 3],
       [0, 0, 0]])