<a href="https://colab.research.google.com/github/abdel2ty/IntenseAI_Notebooks_v1/blob/main/linear_algebra_with_numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<a href="https://www.zero-grad.com/">
         <img alt="Zero Grad" src="https://i.postimg.cc/y8LZ0CM6/linear-Algebra.png" >
      </a>

# Matrix Operations (Element by Element)

In [ ]:
import numpy as np

###Addition

In [ ]:
A = np.array([[10, 20, 30],
              [15, 25, 35]])
A.shape

(2, 3)

In [ ]:
B = np.array([[-10, 5, -1],
              [100, 4, 88]])

In [ ]:
C = A + B
C

array([[  0,  25,  29],
       [115,  29, 123]])

In [ ]:
A +=B
A

array([[  0,  25,  29],
       [115,  29, 123]])

In [ ]:
A +=B
np.add(A,B,A)

array([[-20,  35,  27],
       [315,  37, 299]])

In [ ]:
A

array([[-20,  35,  27],
       [315,  37, 299]])

In [ ]:
A[0]

array([-20,  35,  27])

In [ ]:
# Adding Vectors
A[0] + B[1]

array([ 80,  39, 115])

In [ ]:
# Random Array
E = np.random.rand(3,3)
E

array([[0.21089324, 0.41670339, 0.50548132],
       [0.43544887, 0.73477798, 0.36061936],
       [0.97889696, 0.01760578, 0.96285742]])

In [ ]:
#C + E

In [ ]:
#C[:,0] + E[:,0]

In [ ]:
C

array([[  0,  25,  29],
       [115,  29, 123]])

In [ ]:
# With Scalar
C + 10

array([[ 10,  35,  39],
       [125,  39, 133]])

In [ ]:
C + np.array([[10, 10, 10],
             [10, 10, 10]])

array([[ 10,  35,  39],
       [125,  39, 133]])

### Subtraction

In [ ]:
D = A - B
D

array([[-10,  30,  28],
       [215,  33, 211]])

In [ ]:
np.subtract(A,B)

array([[-10,  30,  28],
       [215,  33, 211]])

In [ ]:
# Subtrating Vectors
A[0] - B[1]

array([-120,   31,  -61])

In [ ]:
# With Scalar
A[0] - 5

array([-25,  30,  22])

### Multiplication and Division (Element by Element)

In [ ]:
A * B

array([[  200,   175,   -27],
       [31500,   148, 26312]])

In [ ]:
np.multiply(A,B)

array([[  200,   175,   -27],
       [31500,   148, 26312]])

In [ ]:
# With Scalar
A * 2

array([[-40,  70,  54],
       [630,  74, 598]])

In [ ]:
A/B

array([[  2.        ,   7.        , -27.        ],
       [  3.15      ,   9.25      ,   3.39772727]])

In [ ]:
np.divide(A,B)

array([[  2.        ,   7.        , -27.        ],
       [  3.15      ,   9.25      ,   3.39772727]])

In [ ]:
A / 2

array([[-10. ,  17.5,  13.5],
       [157.5,  18.5, 149.5]])

# Other Element by Element Operations

In [ ]:
A = np.array([[20,  35,  27],
             [315,  37, 299]])

In [ ]:
np.sqrt(A)

array([[ 4.47213595,  5.91607978,  5.19615242],
       [17.74823935,  6.08276253, 17.29161647]])

In [ ]:
np.exp(A)

array([[4.85165195e+008, 1.58601345e+015, 5.32048241e+011],
       [6.34982563e+136, 1.17191424e+016, 7.14578737e+129]])

In [ ]:
np.log(A)

array([[2.99573227, 3.55534806, 3.29583687],
       [5.75257264, 3.61091791, 5.70044357]])