<a href="https://colab.research.google.com/github/abdel2ty/IntenseAI_Notebooks_v1/blob/main/linear_algebra_with_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<a href="https://www.zero-grad.com/">
         <img alt="Zero Grad" src="https://i.postimg.cc/y8LZ0CM6/linear-Algebra.png" >
      </a>

# Scalars, Vectors and Matrices

## The Basics

In [ ]:
# Scalar
x=5

In [ ]:
# Vector
y= [1,2,3,4]  # row or column

In [ ]:
# Matrix
z= [[11, 12, 13],  # row 1
    [21, 22, 23],  # row 2
    [31, 32, 33]]  # row 3
#    c1  c2  c3    -----> Columns
z

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [ ]:
type(z)

list

In [ ]:
# Indexing
z[0][0]   # Indexing start at 0

11

In [ ]:
import numpy as np

## Scalar

In [ ]:
s = 5.25
type(s)

float

In [ ]:
s_arr = np.array(5.5)
print(type(s_arr))
print(s_arr.dtype)
print(s_arr.shape)
print(s_arr.ndim)

<class 'numpy.ndarray'>
float64
()
0


In [ ]:
s_arr = np.array([5])
print(type(s_arr))
print(s_arr.dtype)
print(s_arr.shape)
print(s_arr.ndim)

<class 'numpy.ndarray'>
int32
(1,)
1


In [ ]:
s_arr = np.array([[5]])
print(type(s_arr))
print(s_arr.dtype)
print(s_arr.shape)
print(s_arr.ndim)

<class 'numpy.ndarray'>
int32
(1, 1)
2


## Vector

In [ ]:
v = np.array([1,2,3])
print(v)
print(type(v))
print(v.dtype)
print(v.shape)
print(v.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int32
(3,)
1


In [ ]:
v = np.array([[1,2,3]], dtype = float)
print(v)
print(type(v))
print(v.dtype)
print(v.shape)
print(v.ndim)

[[1. 2. 3.]]
<class 'numpy.ndarray'>
float64
(1, 3)
2


In [ ]:
v2 = v.reshape(3,1)
print(v2)
print(type(v2))
print(v2.dtype)
print(v2.shape)
print(v2.ndim)

[[1.]
 [2.]
 [3.]]
<class 'numpy.ndarray'>
float64
(3, 1)
2


## Matrix

In [ ]:
z

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [ ]:
m = np.array(z)

In [ ]:
print(m)
print(type(m))
print(m.dtype)
print(m.shape)
print(m.ndim)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>
int32
(3, 3)
2


In [ ]:
len(v2)

3

In [ ]:
len(m)

3

In [ ]:
m.shape

(3, 3)

In [ ]:
m.shape[0]

3

In [ ]:
m.shape[1]

3