<a href="https://colab.research.google.com/github/abdel2ty/IntenseAI_Notebooks_v1/blob/main/more_from_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<a href="https://www.zero-grad.com/">
         <img alt="Zero Grad" src="https://i.postimg.cc/y8LZ0CM6/linear-Algebra.png" >
      </a>

# More From Numpy

In [ ]:
import numpy as np

## Zeros

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5, 2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
np.zeros((2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
A = np.array([[10, 20, 30],
              [15, 25, 35]])

In [ ]:
np.min(A, axis=1)

array([10, 15])

In [ ]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0]])

## Ones

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones((3,4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

## Full

In [ ]:
np.full((3,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
np.full_like(A, 2.1)

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.full_like(A, 5)

array([[5, 5, 5],
       [5, 5, 5]])

## Empty

In [ ]:
np.empty([2, 2])

array([[5.e-324, 5.e-324],
       [5.e-324, 0.e+000]])

In [ ]:
np.empty_like(A)

array([[47244176,        0,        0],
       [       0,        0,        0]])

## Identity

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

## Range

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
np.arange(3,7)

array([3, 4, 5, 6])

In [ ]:
np.arange(3,10,2)

array([3, 5, 7, 9])

## Linspace

In [ ]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.linspace(2.0, 3.0)  # num = 50 (default)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

## Random


> Return random floats in the half-open interval [0.0, 1.0)

In [ ]:
np.random.random((5,3))

array([[0.85630653, 0.98031005, 0.00572769],
       [0.41299289, 0.3440461 , 0.28514077],
       [0.69148162, 0.71152593, 0.62814152],
       [0.352887  , 0.77344188, 0.04296074],
       [0.76415545, 0.09226768, 0.24408213]])

 ### Uniform Distribution
 > Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [ ]:
np.random.rand(3,2,2)

array([[[0.15115447, 0.24695536],
        [0.47437519, 0.16353076]],

       [[0.26170909, 0.60601585],
        [0.80113122, 0.41000066]],

       [[0.27986726, 0.12100981],
        [0.79040915, 0.15102978]]])

### Normal Distribution
> Return a sample (or samples) from the “standard normal” distribution.

In [ ]:
np.random.randn(2, 4)

array([[-0.98376226, -0.07246478,  0.61890584, -1.053693  ],
       [ 1.16923157, -2.97086274, -0.47781536, -0.4609783 ]])

In [ ]:
np.random.seed(0)
np.random.randn(2, 4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721]])

In [ ]:
np.random.seed(0)
np.random.randn(2, 4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721]])

In [ ]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma, 100)

array([-0.01032189,  0.04105985,  0.01440436,  0.14542735,  0.07610377,
        0.0121675 ,  0.04438632,  0.03336743,  0.14940791, -0.02051583,
        0.03130677, -0.08540957, -0.25529898,  0.06536186,  0.08644362,
       -0.0742165 ,  0.22697546, -0.14543657,  0.00457585, -0.01871839,
        0.15327792,  0.14693588,  0.01549474,  0.03781625, -0.08877857,
       -0.19807965, -0.03479121,  0.0156349 ,  0.12302907,  0.12023798,
       -0.03873268, -0.03023028, -0.1048553 , -0.14200179, -0.17062702,
        0.19507754, -0.05096522, -0.04380743, -0.12527954,  0.07774904,
       -0.16138978, -0.02127403, -0.08954666,  0.03869025, -0.05108051,
       -0.11806322, -0.00281822,  0.04283319,  0.00665172,  0.03024719,
       -0.06343221, -0.03627412, -0.06724604, -0.03595532, -0.08131463,
       -0.17262826,  0.01774261, -0.04017809, -0.16301983,  0.04627823,
       -0.09072984,  0.00519454,  0.07290906,  0.01289829,  0.11394007,
       -0.12348258,  0.04023416, -0.06848101, -0.08707971, -0.05

In [ ]:
np.random.normal(3, 2.5, size=(2, 4))

array([[7.80735507, 6.70128698, 7.6688974 , 5.26511165],
       [0.84693579, 7.77516238, 2.32999157, 5.00614099]])

In [ ]:
np.random.normal(size=(2, 4))  # mean = 0, std = 0.1 (default)

array([[ 0.94725197, -0.15501009,  0.61407937,  0.92220667],
       [ 0.37642553, -1.09940079,  0.29823817,  1.3263859 ]])

### Integer Random

> Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).


In [ ]:
np.random.randint(low = 5, high= 20, size=(2, 4))

array([[ 8, 12, 14, 14],
       [14, 12,  8, 19]])

### Seed

In [ ]:
import numpy as np

for i in range(5):
    np.random.seed(42)
    print(np.random.randint(5,10,12))
    print(np.random.rand(3,2))
    print(np.random.random((3,2)))
    print ('***********')

[8 9 7 9 9 6 7 7 7 9 8 7]
[[0.02058449 0.96990985]
 [0.83244264 0.21233911]
 [0.18182497 0.18340451]]
[[0.30424224 0.52475643]
 [0.43194502 0.29122914]
 [0.61185289 0.13949386]]
***********
[8 9 7 9 9 6 7 7 7 9 8 7]
[[0.02058449 0.96990985]
 [0.83244264 0.21233911]
 [0.18182497 0.18340451]]
[[0.30424224 0.52475643]
 [0.43194502 0.29122914]
 [0.61185289 0.13949386]]
***********
[8 9 7 9 9 6 7 7 7 9 8 7]
[[0.02058449 0.96990985]
 [0.83244264 0.21233911]
 [0.18182497 0.18340451]]
[[0.30424224 0.52475643]
 [0.43194502 0.29122914]
 [0.61185289 0.13949386]]
***********
[8 9 7 9 9 6 7 7 7 9 8 7]
[[0.02058449 0.96990985]
 [0.83244264 0.21233911]
 [0.18182497 0.18340451]]
[[0.30424224 0.52475643]
 [0.43194502 0.29122914]
 [0.61185289 0.13949386]]
***********
[8 9 7 9 9 6 7 7 7 9 8 7]
[[0.02058449 0.96990985]
 [0.83244264 0.21233911]
 [0.18182497 0.18340451]]
[[0.30424224 0.52475643]
 [0.43194502 0.29122914]
 [0.61185289 0.13949386]]
***********
