<a href="https://colab.research.google.com/github/abdel2ty/IntenseAI_Notebooks_v1/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<a href="https://www.zero-grad.com/">
         <img alt="Zero Grad" src="https://i.postimg.cc/y8LZ0CM6/linear-Algebra.png" >
      </a>

Reference : https://libguides.ntu.edu.sg/python/

In [ ]:
import numpy as np

# (1) Create a rank 2 array that resembles the matrix below.  
Note: Rank is the number of dimensions of array (rank 2 = 2D)


Create a rank 2 array that resembles the matrix below.  

```
[[11 12 13 14]
 [15 16 17 18]]
```

In [ ]:
# Try Here


## Solution (1)

In [ ]:
# 1. Create a rank 2 (2D) array
myArray = np.array([[11,12,13,14],[15,16,17,18]])
print(myArray, "\n")

# 2. Find out the shape of the above array
print("The shape of the array is:")
print(myArray.shape)

[[11 12 13 14]
 [15 16 17 18]] 

The shape of the array is:
(2, 4)


# (2) Creating arrays with NumPy functions

1. Create an array with 4 rows and 3 columns of zeros.
2. Create an array of ones that has 3 rows and 4 columns.
3. Create an array containing integers 4 to 13 inclusive.
4. Create an array from 0 to 4.5 in step of 1.5.
5. Create a 2 by 2 array containing '4' in each position.
6. Create Identity matrix of size 4.
7. Create Diagonal matrix with [10,12] as the diagonals.
8. Create a 3 by 3 array with random floats in [0, 10].
9. Create a 3 by 3 array with random integers in [10, 20]

In [ ]:
# Try Here


## Solution (2)

In [ ]:
#1
zero = np.zeros((4,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#2
one = np.ones((3,4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#3
range1 = np.arange(4,14)
print(range1)

[ 4  5  6  7  8  9 10 11 12 13]


In [ ]:
#4
print(np.linspace(0, 4.5, 4))
print(np.arange(0, 5, 1.5))

[0.  1.5 3.  4.5]
[0.  1.5 3.  4.5]


In [ ]:
#5
print(np.full((2,2),4))

[[4 4]
 [4 4]]


In [ ]:
#6
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#7
print(np.diag([10,12]))

[[10  0]
 [ 0 12]]


In [ ]:
print(np.diag([10, 12, 15, 20]))

[[10  0  0  0]
 [ 0 12  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]


In [ ]:
#8
print(np.random.random((3,3))*10)
print('*'*50)
print(np.random.uniform(low=0, high=10, size=(3,3)))

[[8.22851426 8.32709879 4.78451584]
 [4.48919502 3.26704199 6.43054089]
 [3.95052331 7.64168777 9.78901381]]
**************************************************
[[1.34266788 0.84577827 5.52141841]
 [8.3774601  8.79519844 9.47341615]
 [7.02867017 2.29510196 2.05794636]]


In [ ]:
#9
print(np.random.randint(low=10, high=20, size=(3,3)))
# You can write easily like below
#print(np.random.randint(10, 20, (3,3)))

[[16 11 18]
 [10 11 15]
 [14 19 14]]


# (3) Array Slicing


1. Use this array for the following practice:
```
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
```

    a. Get a subarray of the first row and first 2 columns. Your results should look like this:
```
[11 12]
```

    b. Change all elements in 1st and second row to 0. Your results should look like this:
```
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]
 ```

2. Create an array that contains `[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]` and reverse the order.

In [ ]:
# Try Here


## Solution (3)

In [ ]:
#1a
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
myArray_new = myArray[0,:2]
print(myArray_new)

[11 12]


In [ ]:
#1b
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
myArray[:2,:] = 0
print(myArray)

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


In [ ]:
#2
myArray = np.arange(21)
print(myArray[::-1])

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


# (4) Array Reshaping

Use this array for the following practice:

`myArray = np.array([[11,12,13], [14,15,16]])`

Reshape the array to an array with 3 rows. Your results should look like this:

```
[[11 12]
 [13 14]
 [15 16]]
 ```



In [ ]:
# Try Here


## Solution (4)

In [ ]:
myArray = np.array([[11,12,13],[14,15,16]])
print(myArray)
print()

myArray = myArray.reshape(3,-1)   # .reshape automatically detects the column number. We can simply just replace the column number with -1.
print(myArray)

[[11 12 13]
 [14 15 16]]

[[11 12]
 [13 14]
 [15 16]]


# (5) Math with NumPy

## 5.a Use this array for the following practice:
```
myArray = np.arange(10)
```

1. Find the square of every number in array

2. Find the square root of every number in array

3. Multiply the square of each number in array with its respective square root

In [ ]:
# Try Here


### Solution (5a)

In [ ]:
myArray = np.arange(10)

# 1. Find the square of every number in array
sq = myArray**2
print("Question 1:")
print(sq, "\n")


# 2. Find the square root of every number in array
print("Question 2:")
sqrt = np.sqrt(myArray)
print(sqrt, "\n")

# 3. Multiply the square of each number in array with its respective square root
print("Question 3:")
print(sq*sqrt)

Question 1:
[ 0  1  4  9 16 25 36 49 64 81] 

Question 2:
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 

Question 3:
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


## 5.b Use this array for the following practice:

```
myArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

1. Find the mean of this array

2. Find the standard deviation by rows

3. Find the maximum value in the array

In [ ]:
# Try Here


### Solution (5b)

In [ ]:
myArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("The original array:\n", myArray, "\n")

# 1. Find the mean of array
print("The mean of elements in array:\n", myArray.mean(), "\n")
print("The mean of elements in array:\n", np.mean(myArray), "\n")           # Overall Mean
print("The mean of every column in array:\n", np.mean(myArray, axis =0), "\n")  # Mean for every column (Through rows)
print("The mean of every row in array:\n", np.mean(myArray, axis =1), "\n")  # Mean for every row (Through columns)

The original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

The mean of elements in array:
 5.0 

The mean of elements in array:
 5.0 

The mean of every column in array:
 [4. 5. 6.] 

The mean of every row in array:
 [2. 5. 8.] 



In [ ]:
# 2. Find the standard deviation by rows
print("The SD of elements by row:\n",np.std(myArray,axis=1), "\n")

# 3. Find the maximum value of the array
print("The max of all elements:\n", np.max(myArray), "\n")   # you can also use axis 0 or 1

The SD of elements by row:
 [0.81649658 0.81649658 0.81649658] 

The max of all elements:
 9 



# (6) Combining 2 arrays

 Combine the following arrays horizontally and vertically


```
x = np.arange(10).reshape(5,-1)
y = np.arange(10,20).reshape(5,-1)
```



In [ ]:
# Try Here


## Solution (6)

In [ ]:
x = np.arange(10).reshape(5,-1)
y = np.arange(10,20).reshape(5,-1)
print('x:\n', x)
print()
print('y:\n',y)

x:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

y:
 [[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [ ]:
# Combine them horizontally
print("Combined array is:\n",np.concatenate([x,y], axis=1))

Combined array is:
 [[ 0  1 10 11]
 [ 2  3 12 13]
 [ 4  5 14 15]
 [ 6  7 16 17]
 [ 8  9 18 19]]


In [ ]:
# Combine them horizontally (another method)
print("Combined array is:\n",np.hstack([x,y]))

Combined array is:
 [[ 0  1 10 11]
 [ 2  3 12 13]
 [ 4  5 14 15]
 [ 6  7 16 17]
 [ 8  9 18 19]]


In [ ]:
# Combine them vertically
print("Combined array is:\n",np.concatenate([x,y], axis=0))

Combined array is:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [ ]:
# Combine them vertically (another method)
print("Combined array is:\n",np.vstack([x,y]))

Combined array is:
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


# (7) Arrays Appending

## (7a) Adding 1 element to 1D arrays




In [ ]:
x = np.array([1,2,3,4])
x = np.append(x,12)
print(x)


[ 1  2  3  4 12]


## (7b) Adding multiple elements to 1D arrays


In [ ]:
x = np.array([1,2,3,4])
print(x)

x = np.append(x,[12,13])
print(x)

[1 2 3 4]
[ 1  2  3  4 12 13]


## (7c) Adding extra rows to 2D arrays

In [ ]:
y = np.array([[1,2],[3,4]])
y = np.append(y,[[11,12]],axis = 0)
print(y)

[[ 1  2]
 [ 3  4]
 [11 12]]


## (7d) Adding extra columns to 2D arrays

In [ ]:
y = np.array([[1,2],[3,4]])
y = np.append(y,[[11],[12]],axis = 1)
print(y)

[[ 1  2 11]
 [ 3  4 12]]


# (8) Arrays Inserting

**Note:**  `np.append` only adds elements to the last row/column while `np.insert` lets you add elements in a specific spot.

## (8a) Insert elements to 1D arrays

In [ ]:
x = np.array([1,2,3,4])
x = np.insert(x,2,[11,12,13])
print(x)

[ 1  2 11 12 13  3  4]


## (8b) Insert elements to a row in 2D arrays


In [ ]:
y = np.array([[1,2],[3,4]])
print("The original array:\n", y, "\n")

y = np.insert(y,1,[11,12],axis = 0)
print("The updated array:\n", y, "\n")


The original array:
 [[1 2]
 [3 4]] 

The updated array:
 [[ 1  2]
 [11 12]
 [ 3  4]] 



## (8c) Insert elements in a column to 2D arrays

In [ ]:
y = np.array([[1,2],[3,4]])
print("The original array:\n", y, "\n")

y = np.insert(y,2,11,axis = 1)
print("The updated  array:\n", y, "\n")

The original array:
 [[1 2]
 [3 4]] 

The updated  array:
 [[ 1  2 11]
 [ 3  4 11]] 



## Exercise
1. Add 1 column of 1 to this array: myArray = np.zeros((2,2))
2. Add 2 rows of 2 to the answer from part 1
3. Remove the last column
4. Remove the last row

In [ ]:
myArray = np.zeros((2,2))
print(myArray, "\n")

# 1. Add 1 column of 1
myArray_1 = np.append(myArray,np.ones((2,1)),axis = 1)
print(myArray_1, "\n")

# 2. Add 2 rows of 2 to the answer from part 1
myArray_2 = np.append(myArray_1,[[2,2,2],[2,2,2]],axis = 0)
print(myArray_2, "\n")

# 3. Remove the last column
myArray_3 = np.delete(myArray_2,2,axis=1)
print(myArray_3, "\n")

# 4. Remove the last row
myArray_4 = np.delete(myArray_3,3,axis=0)
print(myArray_4)

[[0. 0.]
 [0. 0.]] 

[[0. 0. 1.]
 [0. 0. 1.]] 

[[0. 0. 1.]
 [0. 0. 1.]
 [2. 2. 2.]
 [2. 2. 2.]] 

[[0. 0.]
 [0. 0.]
 [2. 2.]
 [2. 2.]] 

[[0. 0.]
 [0. 0.]
 [2. 2.]]


# (9) Deleting elements from arrays

## (9a) Deleting elements from 1D Arrays

In [ ]:
x = np.array([1,2,3,4])
x = np.delete(x,[0,2])      # delete the 2nd and 4th elements
print(x)

[2 4]


## (9b) Deleting elements from 2D Arrays

In [ ]:
y = np.array([[1,2],[3,4]])
print("The original array:")
print(y)
print()

y = np.delete(y, 0, axis = 1)
print("After deleting elements from the first column:")
print(y)

The original array:
[[1 2]
 [3 4]]

After deleting elements from the first column:
[[2]
 [4]]


In [ ]:
y = np.array([[1,2],[3,4]])
print("The original array:")
print(y)
print()

y = np.delete(y, 0, axis = 0)
print("After deleting elements from the first row:")
print(y)

The original array:
[[1 2]
 [3 4]]

After deleting elements from the first row:
[[3 4]]


# (10)  Arrays Sorting

## (10a) Sorting elements in arrays


In [ ]:
x = np.array([3,2,1,4])
print('x :', x)

# When used as a function, the original array stays the same
sorted_x = np.sort(x)
print('sorted_x :', sorted_x)
print('x :', x)


x : [3 2 1 4]
sorted_x : [1 2 3 4]
x : [3 2 1 4]


In [ ]:
x = np.array([3,2,1,4])
print('x :', x)

# When used as a method, the original array changes
x.sort()
print('x after sorting :', x)

x : [3 2 1 4]
x after sorting : [1 2 3 4]


## (10b) Sort by rows or columns


In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])
print("The original array:\n", y, "\n")

# Sort elements in rows
y = np.sort(y,axis = 1)
print("Sort rows:\n", y, "\n")

The original array:
 [[2 7 3]
 [8 3 5]
 [4 0 9]] 

Sort rows:
 [[2 3 7]
 [3 5 8]
 [0 4 9]] 



In [ ]:
y = np.array([[2,7,3],[8,3,5],[4,0,9]])
print("The original array:\n", y, "\n")

# Sort elements in columns
y = np.sort(y,axis = 0)
print("Sort columns:\n", y, "\n")

The original array:
 [[2 7 3]
 [8 3 5]
 [4 0 9]] 

Sort columns:
 [[2 0 3]
 [4 3 5]
 [8 7 9]] 



# (11) Comparing 2 arrays

In [ ]:
x = np.ones(10)
y = np.arange(10)

print("Array X:\n", x, "\n")
print("Array Y:\n", y, "\n")

print("1. The index of elements that are the same in both arrays:")
print(np.where(x == y), "\n")

print("2. The index of elements in x that are bigger than or equal to its corresponding element in y:")
print(np.where(x >= y), "\n")

print("3. The index of elements in x multiplied by 2 that are smaller than its corresponding element in y:")
print(np.where(2*x < y), "\n")

print("4. The index of elements in y that are bigger than 5:")
print(np.where(y > 5), "\n")

Array X:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

Array Y:
 [0 1 2 3 4 5 6 7 8 9] 

1. The index of elements that are the same in both arrays:
(array([1]),) 

2. The index of elements in x that are bigger than or equal to its corresponding element in y:
(array([0, 1]),) 

3. The index of elements in x multiplied by 2 that are smaller than its corresponding element in y:
(array([3, 4, 5, 6, 7, 8, 9]),) 

4. The index of elements in y that are bigger than 5:
(array([6, 7, 8, 9]),) 



In [ ]:
x = np.ones(10)
y = np.arange(10)

print("Array A:\n", x, "\n")
print("Array B:\n", y, "\n")

print("Which element in y is bigger than 3?\n")
print(y > 3, "\n")
print("Elements 0 to 3 smaller than 3, while elements 4 to 9 are bigger than 3.\n")

print("List the index of elements in y that are bigger than 3: \n")
print(y[y>3])

Array A:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

Array B:
 [0 1 2 3 4 5 6 7 8 9] 

Which element in y is bigger than 3?

[False False False False  True  True  True  True  True  True] 

Elements 0 to 3 smaller than 3, while elements 4 to 9 are bigger than 3.

List the index of elements in y that are bigger than 3: 

[4 5 6 7 8 9]


In [ ]:
print(y[np.where(y>3)])     # alternative to y[y>3]

[4 5 6 7 8 9]
