<a href="https://colab.research.google.com/github/abdel2ty/IntenseAI_Notebooks_v1/blob/main/r1_live_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])


In [ ]:
# Element Wise Multiplication
v1 * v2

array([ 4, 10, 18])

In [ ]:
# Dot Product
v1.dot(v2)

np.int64(32)

In [ ]:
v1 @ v2

np.int64(32)

In [ ]:
4 + 10 + 18

32

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])


In [ ]:
m1

array([[1, 2],
       [3, 4]])

In [ ]:
m2

array([[5, 6],
       [7, 8]])

In [ ]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [ ]:
m1 @ m2

array([[19, 22],
       [43, 50]])

In [ ]:
m3 = np.array([[2], [4]])
m3

array([[2],
       [4]])

In [ ]:
m1 @ m3  # m1.shape = (2, 2) and m3.shape = (2, 1)

array([[10],
       [22]])

In [ ]:
m3.T

array([[2, 4]])

In [ ]:
m3.T.shape

(1, 2)

In [ ]:
m3.T @ m1  # m3.T.shape = (1, 2) and m1.shape = (2, 2)

array([[14, 20]])

In [ ]:
fruits_qty = np.array([[13, 9 ,7 ,15],
                   [8, 7, 4, 6],
                   [6, 4, 0, 3]])

fruits_price = np.array([3, 4, 2])

In [ ]:
monday_qty = fruits_qty[:, 0]
monday_qty

array([13,  8,  6])

In [ ]:
monday_total = monday_qty @ fruits_price
monday_total

np.int64(83)

In [ ]:
monday_sales = monday_qty * fruits_price
monday_sales

array([39, 32, 12])

In [ ]:
# Random (Uniform Distribution)
np.random.rand(2, 3)

array([[0.33463592, 0.54403923, 0.28263534],
       [0.65091455, 0.5731775 , 0.46389622]])

In [ ]:
# Random (Integer Distribution)
np.random.randint(low = 100, high= 150, size = (2, 3))

array([[129, 107, 113],
       [101, 102, 129]])

In [ ]:
# Random (Standard Normal Distribution) (mean =0, std = 1)
np.random.randn(2, 3)

array([[ 1.22222078,  1.49019275,  0.05852353],
       [ 0.36479494, -0.15153851,  0.26481853]])

In [ ]:
# Random (Normal Distribution)
np.random.normal(loc = 100, scale = 10, size = (2, 3))

array([[102.84122642,  98.14242313, 104.16954838],
       [ 94.14861182, 101.43334733, 101.81640571]])